name: Prevent Node Modules Upload

on:
  pull_request:
    paths:
      - '**/node_modules/**'

jobs:
  check_node_modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for node_modules in Pull Request
        run: |
          if git diff --name-only origin/main | grep -q "node_modules/"; then
            echo "🚨 The pull request contains 'node_modules/' directory, which is not allowed."
            exit 1
          else
            echo "✅ No 'node_modules/' directory detected."
          fi
